# Generated by Django 5.0.6 on 2026-03-11 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreneauDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour_semaine', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')])),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('duree_consultation', models.IntegerField(default=30, help_text='Durée en minutes')),
                ('actif', models.BooleanField(default=True)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='accounts.profilmedecin')),
            ],
            options={
                'verbose_name': 'Créneau disponible',
                'ordering': ['jour_semaine', 'heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField()),
                ('duree', models.IntegerField(default=30, help_text='Durée en minutes')),
                ('type_rdv', models.CharField(choices=[('consultation', 'Consultation'), ('suivi', 'Suivi'), ('urgence', 'Urgence'), ('controle', 'Contrôle')], default='consultation', max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('annule', 'Annulé'), ('termine', 'Terminé'), ('absent', 'Patient absent')], default='en_attente', max_length=20)),
                ('motif', models.TextField(help_text='Motif de la consultation')),
                ('notes_medecin', models.TextField(blank=True, help_text='Notes du médecin (post-consultation)')),
                ('symptomes', models.TextField(blank=True, help_text='Symptômes décrits par le patient')),
                ('rappel_envoye', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rdv_medecin', to='accounts.profilmedecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rdv_patient', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
                'ordering': ['-date_heure'],
            },
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_emission', models.DateField(auto_now_add=True)),
                ('valide_jusqu', models.DateField(blank=True, null=True)),
                ('rendez_vous', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnance', to='appointments.rendezvous')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notif', models.CharField(choices=[('rdv_confirme', 'RDV Confirmé'), ('rdv_annule', 'RDV Annulé'), ('rappel', 'Rappel RDV'), ('info', 'Information')], max_length=20)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('lu', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('rdv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.rendezvous')),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
    ]
